In an observable we simply won't set an interval that spits out number at regular interval. We would
usually make an HTTP request in that. So, many a times, that request may even fail or some error may
occur. When that happens, we don't want to call, observer.next(). We would rather call the 'error' method.

Let's modify the example from the previous file to handle error.

	const customIntervalObservable = Observable.create(observer => {
		let count = 0;
		setInterval(() => {

			// Assume, if count > 3, it is an error, just for example purposes
			if (count > 3)
				observer.error(new Error('Count is greater than 3!'))

			observer.next(count++);
		}, 1000);
	});
	// When we call the 'error' message on the observer, the observer stops observing. So, we don't
	// need to 'unsubscribe' from the observable. However, it won't be an error if we 'unsubscribe'
	// anyway.

	this.observer = customIntervalObservable.subscribe(data => {
		console.log(data);
	}, error => {
		alert(error.message);
	});
	// The second argument to the 'subscribe' method is also a function, that should take one argument.
	// That function is called if 'observer.error()' is invoked by its observable.


Similarly, we have the 'complete' method. When the observable invokes 'complete' method, the third
argument, passed to the 'subscribe' method (which is also a function, with no arguments) of that
observable, is invoked. After the observable has invoked the complete method on the observer, it then
completes. The observer is also unsubscribed. We don't need to manually unsubscribe it, but there is no
harm in doing it.

NOTE: Even though, observer.error() terminates the observable, the 'complete' method is not called or
	  invoked. Only the function, passed as second argument, is invoked.
